# ~/src/box/box-cmds.sh
#!/bin/bash
set -euo pipefail
export LC_ALL=C

box_init() {
  need_root
  command install -d "$DB" "$MAN" "$META" "$LOGS" "$STATE"
  echo "box: ok: initialized $DB"
}

box_new() {
  [ -r /dev/tty ] || die "error: no controlling tty"

  prompt() {
    local _q="$1" _def="${2-}" _ans=""
    if [ -n "$_def" ]; then
      printf "%s [%s]: " "$_q" "$_def" >&2
    else
      printf "%s: " "$_q" >&2
    fi

    IFS= read -r _ans </dev/tty || _ans=""
    if [ -z "${_ans:-}" ]; then printf "%s" "$_def"; else printf "%s" "$_ans"; fi
  }

  PKG="$(prompt "PKG name" "")"
  [ -n "$PKG" ] || die "PKG required"

  VER="$(prompt "Version" "")"
  [ -n "$VER" ] || die "VER required"

  local SRC_DEFAULT=""
  SRC_DEFAULT="$(guess_src "$PKG" "$VER")"
  SRC="$(prompt "Source tarball path" "$SRC_DEFAULT")"

  DESC="$(prompt "Short description" "$PKG")"
  PREFIX="$(prompt "Install prefix" "/usr")"
  TESTS="$(prompt "Run tests? (y/n)" "n")"

  case "$SRC" in
    *.tar.lz) EXTRACT='lzip -dc "$SRC" | tar -xf - -C "$WORKDIR"' ;;
    *.tar.gz|*.tgz|*.tar.xz|*.tar.bz2|*.tar) EXTRACT='tar -xf "$SRC" -C "$WORKDIR"' ;;
    *) EXTRACT='tar -xf "$SRC" -C "$WORKDIR"' ;;
  esac

  if [ "$TESTS" = "y" ] || [ "$TESTS" = "Y" ]; then
    CHECK='make check'
  else
    CHECK=': # make check'
  fi

  OUT_DEFAULT="$HOME/ls-box/recipes/$PKG-$VER.sh"
  OUT="$(prompt "Output recipe path" "$OUT_DEFAULT")"
  mkdir -p "$(dirname "$OUT")"

  cat >"$OUT" <<EOF_RECIPE
# Generated by box new
PKG=$PKG
VER=$VER
SRC=$SRC
DESC="$DESC"

build() {
  : "${WORKDIR:=/tmp/box-work/\$PKG-\$VER}"
  rm -rf "\$WORKDIR"
  command install -d "\$WORKDIR"

  $EXTRACT

  TOPDIR="\$(find "\$WORKDIR" -mindepth 1 -maxdepth 1 -type d | sed -n '1p')"
  [ -n "\$TOPDIR" ] || { echo "no topdir after extract" >&2; exit 1; }
  cd "\$TOPDIR"

  if [ -x ./configure ]; then
    ./configure --prefix=$PREFIX
  fi
  make
  $CHECK
}

pkg_install() {
  TOPDIR="\$(find "\$WORKDIR" -mindepth 1 -maxdepth 1 -type d | sed -n '1p')"
  [ -n "\$TOPDIR" ] || { echo "no topdir for install" >&2; exit 1; }
  cd "\$TOPDIR"
  make DESTDIR="\$DESTDIR" install
}
EOF_RECIPE

  chmod 644 "$OUT"
  echo "ok: wrote $OUT"
}

box_add() {
  need_root
  [ $# -ge 1 ] || die "usage: box add <recipe> [--force]"
  local force=no
  [ "${2-}" = "--force" ] && force=yes

  load_recipe "$1"
  : "${PKG:?}" "${VER:?}" "${SRC:?}"
  PKGID="$PKG-$VER"

  stage_dir
  WORKDIR="/tmp/box-work/$PKG-$VER"

  command install -d "$LOGS"
  LOG="$LOGS/$PKGID.$(date +%Y%m%d-%H%M%S).log"
  : >"$LOG"

  run_step() {
    local step="$1" rc
    type "$step" >/dev/null 2>&1 || die "recipe missing $step()"

    # IMPORTANT: tee must not mask failures
    set -o pipefail
    (
      set -euo pipefail
      "$step"
    ) 2>&1 | tee -a "$LOG"
    rc=$?
    [ "$rc" -eq 0 ] || die "step failed: $step (exit $rc)"
  }

  # Best-effort cleanup of temp dirs unless user opts out
  trap 'box_cleanup' EXIT

  run_step build
  run_step pkg_install

  make_manifest
  check_collisions "$force"
  commit_stage
  write_meta

  echo "box: ok: installed $PKGID"
}

box_rm() {
  need_root
  [ $# -eq 1 ] || die "rm requires <name-ver>"
  local PKGID="$1"
  local mf="$MAN/$PKGID.files"
  [ -f "$mf" ] || die "manifest not found: $mf"

  while IFS= read -r p; do
    local rel target
    rel="${p#./}"
    [ -n "$rel" ] || continue
    target="/$rel"

    case "$target" in
      /|""|"/."|"/.."|*/../*|*/..|*/./*|*/.|*/..) die "invalid or dangerous path in manifest: $target" ;;
    esac
    case "$target" in
      /usr/share/info/dir) continue ;;
    esac

    if [ -L "$target" ] || [ -f "$target" ]; then
      rm -f "$target"
    fi
  done < "$mf"

  if command -v tac >/dev/null 2>&1; then
    TAC="tac"
  else
    die "tac not found (coreutils). Install it or provide a reverse-order tool."
  fi

  $TAC "$mf" | while IFS= read -r p; do
    local rel target
    rel="${p#./}"
    [ -n "$rel" ] || continue
    target="/$rel"

    case "$target" in
      /|""|"/."|"/.."|*/../*|*/..|*/./*|*/.|*/..) die "invalid or dangerous path in manifest: $target" ;;
    esac
    case "$target" in
      /usr/share/info/dir) continue ;;
    esac

    if [ -d "$target" ]; then
      rmdir "$target" 2>/dev/null || true
    fi
  done

  rm -f "$mf" "$META/$PKGID.meta"
  echo "box: ok: removed $PKGID"
}

box_list() {
  ls "$META" 2>/dev/null | sed 's/\.meta$//' | sort
}

box_info() {
  [ $# -eq 1 ] || die "info requires <name-ver>"
  local f="$META/$1.meta"
  [ -f "$f" ] || die "meta not found: $f"
  cat "$f"
}

box_world() {
  need_root
  [ $# -ge 1 ] || die "world requires a list file"

  local list force runid out rc
  list="$1"
  force="no"
  [ "${2:-}" = "--force" ] && force="yes"

  [ -f "$list" ] || die "list not found: $list"

  runid="world-$(date +%Y%m%d-%H%M%S 2>/dev/null || date)"
  out="$STATE/$runid.log"

  mkdir -p "$STATE" || die "cannot create state dir: $STATE"

  set -o pipefail
  {
    echo "== box world =="
    echo "LIST=$list"
    echo "DATE=$(date -Is 2>/dev/null || date)"
    echo

    while IFS= read -r line; do
      case "$line" in
        ""|\#*) continue ;;
      esac

      echo "--> $line"
      if [ "$force" = "yes" ]; then
        box add "$line" --force || die "world failed on: $line"
      else
        box add "$line" || die "world failed on: $line"
      fi
      echo
    done < "$list"
  } 2>&1 | tee "$out"
  rc=$?
  set +o pipefail || true

  [ $rc -eq 0 ] || die "world run failed (rc=$rc). log: $out"
  echo "box: ok: world run logged to $out"
}

main() {
  local cmd="${1:-}"
  shift || true

  case "$cmd" in
    init) box_init ;;
    new) box_new ;;
    add) box_add "$@" ;;
    rm) box_rm "$@" ;;
    adopt) box_adopt "$@" ;;
    own) box_own "$@" ;;
    list) box_list ;;
    info) box_info "$@" ;;
    world) box_world "$@" ;;
    ""|-h|--help|help) usage ;;
    *) die "unknown command: $cmd (try: box --help)" ;;
  esac
}
