# ~/src/box/box-cmds.sh
#!/bin/bash
set -euo pipefail
export LC_ALL=C

box_init() {
  need_root
  command install -d "$DB" "$DB/installed" "$MAN" "$META" "$LOGS" "$STATE"
  echo "box: ok: initialized $DB"
}

box_new() {
  [ -r /dev/tty ] || die "error: no controlling tty"

  prompt() {
    local _q="$1" _def="${2-}" _ans=""
    if [ -n "$_def" ]; then
      printf "%s [%s]: " "$_q" "$_def" >&2
    else
      printf "%s: " "$_q" >&2
    fi

    IFS= read -r _ans </dev/tty || _ans=""
    if [ -z "${_ans:-}" ]; then printf "%s" "$_def"; else printf "%s" "$_ans"; fi
  }

  PKG="$(prompt "PKG name" "")"
  [ -n "$PKG" ] || die "PKG required"

  VER="$(prompt "Version" "")"
  [ -n "$VER" ] || die "VER required"

  local SRC_DEFAULT=""
  SRC_DEFAULT="$(guess_src "$PKG" "$VER")"
  SRC="$(prompt "Source tarball path" "$SRC_DEFAULT")"

  DESC="$(prompt "Short description" "$PKG")"
  PREFIX="$(prompt "Install prefix" "/usr")"
  TESTS="$(prompt "Run tests? (y/n)" "n")"

  case "$SRC" in
    *.tar.lz) EXTRACT='lzip -dc "$SRC" | tar -xf - -C "$WORKDIR"' ;;
    *.tar.gz|*.tgz|*.tar.xz|*.tar.bz2|*.tar) EXTRACT='tar -xf "$SRC" -C "$WORKDIR"' ;;
    *) EXTRACT='tar -xf "$SRC" -C "$WORKDIR"' ;;
  esac

  if [ "$TESTS" = "y" ] || [ "$TESTS" = "Y" ]; then
    CHECK='make check'
  else
    CHECK=': # make check'
  fi

  OUT_DEFAULT="$HOME/ls-box/recipes/$PKG-$VER.sh"
  OUT="$(prompt "Output recipe path" "$OUT_DEFAULT")"
  mkdir -p "$(dirname "$OUT")"

  cat >"$OUT" <<EOF_RECIPE
# Generated by box new
PKG=$PKG
VER=$VER
SRC=$SRC
DESC="$DESC"

build() {
  : "${WORKDIR:=/tmp/box-work/\$PKG-\$VER}"
  rm -rf "\$WORKDIR"
  command install -d "\$WORKDIR"

  $EXTRACT

  TOPDIR="\$(find "\$WORKDIR" -mindepth 1 -maxdepth 1 -type d | sed -n '1p')"
  [ -n "\$TOPDIR" ] || { echo "no topdir after extract" >&2; exit 1; }
  cd "\$TOPDIR"

  if [ -x ./configure ]; then
    ./configure --prefix=$PREFIX
  fi
  make
  $CHECK
}

pkg_install() {
  TOPDIR="\$(find "\$WORKDIR" -mindepth 1 -maxdepth 1 -type d | sed -n '1p')"
  [ -n "\$TOPDIR" ] || { echo "no topdir for install" >&2; exit 1; }
  cd "\$TOPDIR"
  make DESTDIR="\$DESTDIR" install
}
EOF_RECIPE

  chmod 644 "$OUT"
  echo "ok: wrote $OUT"
}

box_record_install() {
  local inst
  inst="$DB/installed/$PKGID"

  command install -d "$DB/installed" "$inst"

  [ -f "$META/$PKGID.meta" ]     || die "missing meta: $META/$PKGID.meta"
  [ -f "$MAN/$PKGID.files" ]     || die "missing files manifest: $MAN/$PKGID.files"
  [ -f "$MAN/$PKGID.payload" ]   || die "missing payload manifest: $MAN/$PKGID.payload"
  [ -f "$MAN/$PKGID.dirs" ]      || die "missing dirs manifest: $MAN/$PKGID.dirs"

  cp -f -- "$META/$PKGID.meta"     "$inst/meta"
  cp -f -- "$MAN/$PKGID.files"    "$inst/files"
  cp -f -- "$MAN/$PKGID.payload"  "$inst/payload"
  cp -f -- "$MAN/$PKGID.dirs"     "$inst/dirs"

  # Optional: keep the build log with the install record
  [ -n "${LOG:-}" ] && [ -f "$LOG" ] && cp -f -- "$LOG" "$inst/install.log" || true
}

# --- Dependency helpers (v1) ---

installed_has_pkg() {
  # true if any installed meta has PKG=<name>
  local name="$1" mf
  [ -n "$name" ] || return 1
  [ -d "$DB/installed" ] || return 1

  for mf in "$DB/installed"/*/meta; do
    [ -f "$mf" ] || continue
    if grep -qxF "PKG=$name" "$mf"; then
      return 0
    fi
  done
  return 1
}

pkg_name_for_pkgid() {
  # echoes PKG from installed meta (preferred), else falls back to PKGID prefix
  local pkgid="$1" mf
  mf="$DB/installed/$pkgid/meta"
  if [ -f "$mf" ]; then
    awk -F= '$1=="PKG"{print $2; exit}' "$mf" 2>/dev/null || true
    return 0
  fi
  printf "%s\n" "${pkgid%-*}"
}

deps_line_for_pkgid() {
  # echoes the DEPENDS line value (space-separated) if present
  local pkgid="$1" mf
  mf="$DB/installed/$pkgid/meta"
  [ -f "$mf" ] || return 1
  awk -F= '$1=="DEPENDS"{sub(/^DEPENDS=/,""); print $2; exit}' "$mf" 2>/dev/null || true
}

check_depends_installed_or_die() {
  # reads DEPENDS from current recipe environment (array) and validates installed set
  if ! declare -p DEPENDS >/dev/null 2>&1; then
    return 0
  fi

  local dep missing=0
  for dep in "${DEPENDS[@]}"; do
    [ -n "${dep:-}" ] || continue
    if ! installed_has_pkg "$dep"; then
      echo "box: missing dependency: $dep" >&2
      missing=1
    fi
  done

  [ "$missing" -eq 0 ] || die "dependency check failed"
}

check_reverse_deps_or_die() {
  # refuses removal if any installed package depends on target PKG
  local target_pkg="$1"
  [ -n "$target_pkg" ] || die "internal: missing target pkg name for reverse-dep check"

  local mf pkgid deps dependers=""
  [ -d "$DB/installed" ] || return 0

  for mf in "$DB/installed"/*/meta; do
    [ -f "$mf" ] || continue
    pkgid="$(basename "$(dirname "$mf")")"

    deps="$(awk -F= '$1=="DEPENDS"{print $2; exit}' "$mf" 2>/dev/null || true)"
    [ -n "${deps:-}" ] || continue

    case " $deps " in
      *" $target_pkg "*)
        dependers="${dependers}${dependers:+$'\n'}$pkgid"
        ;;
    esac
  done

  if [ -n "$dependers" ]; then
    echo "box: refusing to remove '$target_pkg' — required by:" >&2
    echo "$dependers" >&2
    die "remove blocked by reverse dependencies"
  fi
}

box_add() {
  need_root
  [ $# -ge 1 ] || die "usage: box add <recipe> [--force]"
  local force=no
  [ "${2-}" = "--force" ] && force=yes

  load_recipe "$1"
  : "${PKG:?}" "${VER:?}"
  : "${SRC:=}"
  PKGID="$PKG-$VER"

  check_depends_installed_or_die

  stage_dir
  WORKDIR="/tmp/box-work/$PKG-$VER"

  command install -d "$LOGS"
  LOG="$LOGS/$PKGID.$(date +%Y%m%d-%H%M%S).log"
  : >"$LOG"

  run_step() {
    local step="$1" rc
    type "$step" >/dev/null 2>&1 || die "recipe missing $step()"

    # IMPORTANT: tee must not mask failures
    set -o pipefail
    (
      set -euo pipefail
      "$step"
    ) 2>&1 | tee -a "$LOG"
    rc=$?
    [ "$rc" -eq 0 ] || die "step failed: $step (exit $rc)"
  }

  # Best-effort cleanup of temp dirs unless user opts out
  trap 'box_cleanup' EXIT

  run_step build
  run_step pkg_install

  make_manifest
  write_meta
  check_collisions "$force"
  commit_stage
  owners_register_payload
  box_record_install

  echo "box: ok: installed $PKGID"
}

box_rm() {
  need_root
  [ $# -eq 1 ] || die "rm requires <name-ver>"
  local PKGID="$1"

  local target_pkg=""
  target_pkg="$(pkg_name_for_pkgid "$PKGID")"
  check_reverse_deps_or_die "$target_pkg"

  local inst="$DB/installed/$PKGID"
  local payload dirs

  [ -d "$inst" ] || die "not installed: $PKGID"

  payload="$inst/payload"
  dirs="$inst/dirs"

  [ -f "$payload" ] || die "payload manifest not found: $payload"
  [ -f "$dirs" ] || die "dirs manifest not found: $dirs"

  owners_unregister_payload_from_file "$PKGID" "$payload"
  owners_prune_pkgid "$PKGID"   # optional: cleans any strays

  # Remove files/symlinks
  while IFS= read -r p; do
    local rel target
    rel="${p#./}"
    [ -n "$rel" ] || continue
    target="/$rel"

    case "$target" in
      /|""|"/."|"/.."|*/../*|*/..|*/./*|*/.|*/..) die "invalid or dangerous path in manifest: $target" ;;
    esac
    case "$target" in
      /usr/share/info/dir) continue ;;
    esac

    # payload should only contain files/symlinks, but stay defensive
    if [ -d "$target" ] && [ ! -L "$target" ]; then
      continue
    fi

    if [ -L "$target" ] || [ -f "$target" ]; then
      rm -f -- "$target"
    fi
  done < "$payload"

  # Prune directories (dirs manifest is already deepest-first)
  while IFS= read -r p; do
    local rel target
    rel="${p#./}"
    [ -n "$rel" ] || continue
    target="/$rel"

    case "$target" in
      /|""|"/."|"/.."|*/../*|*/..|*/./*|*/.|*/..) die "invalid or dangerous path in dirs manifest: $target" ;;
    esac

    if [ -d "$target" ]; then
      rmdir -- "$target" 2>/dev/null || true
    fi
  done < "$dirs"

  # Remove install record (authoritative). Also clean legacy crumbs if present.
  rm -rf -- "$inst" 2>/dev/null || true
  rm -f -- "$MAN/$PKGID.files" "$MAN/$PKGID.payload" "$MAN/$PKGID.dirs" "$META/$PKGID.meta" 2>/dev/null || true

  echo "box: ok: removed $PKGID"
}

box_list() {
  ls "$DB/installed" 2>/dev/null | sort
}

box_info() {
  [ $# -eq 1 ] || die "info requires <name-ver>"
  local f="$DB/installed/$1/meta"
  [ -f "$f" ] || die "meta not found: $f"
  cat "$f"
}

box_world() {
  need_root
  [ $# -ge 1 ] || die "world requires a list file"

  local list force runid out rc
  list="$1"
  force="no"
  [ "${2:-}" = "--force" ] && force="yes"

  [ -f "$list" ] || die "list not found: $list"

  runid="world-$(date +%Y%m%d-%H%M%S 2>/dev/null || date)"
  out="$STATE/$runid.log"

  mkdir -p "$STATE" || die "cannot create state dir: $STATE"

  set -o pipefail
  {
    echo "== box world =="
    echo "LIST=$list"
    echo "DATE=$(date -Is 2>/dev/null || date)"
    echo

    while IFS= read -r line; do
      case "$line" in
        ""|\#*) continue ;;
      esac

      echo "--> $line"
      if [ "$force" = "yes" ]; then
        box add "$line" --force || die "world failed on: $line"
      else
        box add "$line" || die "world failed on: $line"
      fi
      echo
    done < "$list"
  } 2>&1 | tee "$out"
  rc=$?
  set +o pipefail || true

  [ $rc -eq 0 ] || die "world run failed (rc=$rc). log: $out"
  echo "box: ok: world run logged to $out"
}

main() {
  local cmd="${1:-}"
  shift || true

  case "$cmd" in
    init) box_init ;;
    new) box_new ;;
    add) box_add "$@" ;;
    rm) box_rm "$@" ;;
    adopt) box_adopt "$@" ;;
    own) box_own "$@" ;;
    list) box_list ;;
    info) box_info "$@" ;;
    world) box_world "$@" ;;
    ""|-h|--help|help) usage ;;
    *) die "unknown command: $cmd (try: box --help)" ;;
  esac
}
